//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.13 at 01:26:07 ���� CST 
//


package com.moto.server.bean;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="u_avatar" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="u_email" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="u_hometown" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="u_id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="u_job" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="u_mobile" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="u_mood" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="u_name" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="u_state" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "User")
public class User {

    @XmlAttribute(name = "u_avatar", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String uAvatar;
    @XmlAttribute(name = "u_email", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String uEmail;
    @XmlAttribute(name = "u_hometown", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String uHometown;
    @XmlAttribute(name = "u_id", required = true)
    protected BigInteger uId;
    @XmlAttribute(name = "u_job", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String uJob;
    @XmlAttribute(name = "u_mobile", required = true)
    protected BigInteger uMobile;
    @XmlAttribute(name = "u_mood", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String uMood;
    @XmlAttribute(name = "u_name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String uName;
    @XmlAttribute(name = "u_state", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String uState;

    /**
     * Gets the value of the uAvatar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUAvatar() {
        return uAvatar;
    }

    /**
     * Sets the value of the uAvatar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUAvatar(String value) {
        this.uAvatar = value;
    }

    /**
     * Gets the value of the uEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUEmail() {
        return uEmail;
    }

    /**
     * Sets the value of the uEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUEmail(String value) {
        this.uEmail = value;
    }

    /**
     * Gets the value of the uHometown property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUHometown() {
        return uHometown;
    }

    /**
     * Sets the value of the uHometown property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUHometown(String value) {
        this.uHometown = value;
    }

    /**
     * Gets the value of the uId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUId() {
        return uId;
    }

    /**
     * Sets the value of the uId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUId(BigInteger value) {
        this.uId = value;
    }

    /**
     * Gets the value of the uJob property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUJob() {
        return uJob;
    }

    /**
     * Sets the value of the uJob property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUJob(String value) {
        this.uJob = value;
    }

    /**
     * Gets the value of the uMobile property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUMobile() {
        return uMobile;
    }

    /**
     * Sets the value of the uMobile property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUMobile(BigInteger value) {
        this.uMobile = value;
    }

    /**
     * Gets the value of the uMood property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUMood() {
        return uMood;
    }

    /**
     * Sets the value of the uMood property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUMood(String value) {
        this.uMood = value;
    }

    /**
     * Gets the value of the uName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUName() {
        return uName;
    }

    /**
     * Sets the value of the uName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUName(String value) {
        this.uName = value;
    }

    /**
     * Gets the value of the uState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUState() {
        return uState;
    }

    /**
     * Sets the value of the uState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUState(String value) {
        this.uState = value;
    }

}
